module.exports.authValidation = require("./auth.validation"); // Auth validations.
// module.exports.adminValidation = require("./auth.validation"); // Notification validation.
module.exports.vehiclesValidation = require("./vehicles.validation"); // vehicles validation.
module.exports.garageValidation = require("./garage.validation"); // garage validation.
module.exports.cusomerValidation = require("./customer.validation"); // customer validation.
module.exports.servicesManagementValidation = require("./services_management.validation"); // services_management validation.
module.exports.garageServicesValidation = require("./garage_services_management.validation"); // garage_services_management validation.
module.exports.appointmentValidation = require("./appointment.validation"); // appointment validation.
module.exports.dashboardValidation = require("./dashboard.validation"); // dashboard validation.
module.exports.accountingValidation = require("./accounting.validation"); // accounting validation.
module.exports.ratingsValidation = require("./ratings.validation"); // ratings validation.
