module.exports = {
  NO_DATA: (str) => `${str} doesn't exist!`,
  REQUIRED: (str) => `${str} is required!`,
  UPDATE_DATA: (str) => `${str} has been update successfully!`,
  DELETE_DATA: (str) => `${str} has been delete successfully!`,
  GET_DATA: (str) => `${str} has been get successfully!`,
  ADD_DATA: (str) => `${str} has been added successfully!`,
  DATA_EXIST: (str) => `${str} already exist!`,
  DEACTIVATED: (str) => `${str} is temporarily deactivated. Please contact the administrator for assistance!`,
  REGISTER: (str) => `${str} registered successfully!`,
  NOT_REGISTER: (str) => `${str} doesn't register!`,
  NO_FOUND: (str) => `${str} not found!`,
  FOUND: (str) => `${str} found!`,
  NOT_MATCH: (str) => `${str} doesn't match, please try again!`,
  MATCH: (str) => `${str} match, successfully!`,
  LOG_IN: `Login successfully!`,
  ROLE_NOT_ALLOWED: `You are not allowed to login!`,
  SOMETHING_WENT_TO_WRONG: "Something went to wrong, please try again later!",
  SENT: (str) => `${str} has been sent to your registered email!`,
  SENT_REQUEST: (str) => `${str} has been sent successfully!`,
  INVALID: (str) => `Invalid ${str} !`,
  EXPIRED: (str) => `Your ${str} has expired. Try again with a new ${str}!`,
  NO_PROVIDE: (str) => `No ${str} provided!`,
  GENERATED: (str) => `${str} generated!`,
  UNAUTHORIZED: "Unauthorized!",
  ADMIN_CREATION_RESTRICTED: "Admin account creation is not permitted.",
  INSUFFICIENT_BALANCE: "Insufficient balance to withdraw!",
  REQUEST_ALREADY_EXISTS: "You cannot submit a new request until your previous request is completed!",
  GARAGE_PENDING_REQUEST: "Your appointment request is still pending with the garage and has not been accepted yet!",
  GARAGE_NO_SERVICES_TAKEN: "You have not availed any services from this garage, so you cannot leave a review or feedback!",
  APPOINTMENT_COMPLETION_RESTRICTED: "The appointment status cannot be marked as completed by the garage. Only the customer or an admin can perform this action!",
  APPOINTMENT_ALREADY_COMPLETED: "This appointment is already completed, so you cannot suggest new services on it!",
  ALREADY_PAID: "The payment for this service has already been completed. No further transactions are required!",
};

// module.exports = { message };
// {
//     "user_not_found": "User not found.",
//     "Company_user_not_found": "Company user not found",
//     "Influencer_not_found": "Influencer_not_found",
//     "user_not_verify": "Your profile is not verified yet please wait for approval.",
//
//     "email_already_taken": "Email already exists",
//     "email_not_verified": "Email not verified. Verify via sign-up to continue.",
//     "account_blocked": "Your account has been blocked, please contact to admin.",
//     "account_not_active": "Your account has been deactivated, please contact to admin",
//     "otp_invalid": "Please enter valid OTP",

//     "invalid_password": "Invalid Password.",
//     "password_reset": "Password is reset successfully.",
//     "password_forgot": "Password is forgot successfully.",
//     "created": "Successfully created.",
//     "updated": "Successfully updated.",
//     "deleted": "Successfully deleted.",
//     "unauthorized": "Unauthorized.",
//     "forbidden": "FORBIDDEN",
//     "notPermission": "You have not permission to access this route.",
//     "otp_verify_success": "OTP verified successfully",
//     "old_password_wrong": "old password is wrong",
//     "company_email_already_taken": "Company email already exists",
//     "user_already_exists": "user already exists",
//     "influencer_already_exists": "Influencer already exist",
//     "phone_number_not_verify": "Phone number not verified",
//     "influencer_phone_number_not_verify": "Influencer phone number not verified",
//     "profile_not_completed": "Your profile has not completed please complete your profile",
//     "phone_number_already_taken": "User phone is already exist.",
//     "Influencer_phone_already_taken": "Influencer phone number is already exist",
//     "company_phone_number_already_taken": "Company phone number already exist",
//     "phone_number_not_registred": "Your mobile number isn't registered in our system",
//     "OTP_VERIFY": "OTP verified successfully. You can now reset your password.",
//     "Email_SEND_SUCCESSFULLY": "A password forget OTP has been sent to your registered email address.",
//     "PASSWORD_CHANGE": "Your password has been updated successfully.",
//     "SUCCESS": "Success.",
//     "DATA_NOT_FOUND": "data not found in database",
//     "INVALID_OTP": "Invalid OTP. Please try again.",
//     "INVALID_CRED": "Invalid credentials",
//     "INVALID_ROLE": "Invalid role of user",
//     "product_not_found": "product not found",
//     "product_name_already_exists": "product already exists",
//     "invalid_email": "Invalid email address",
//     "otp_send_successfully": "OTP has been sent to your email ID",
//     "otp_resend_successfully": "OTP resent to your mail. Please check your mailbox.",
//     "category_not_selected": "Category not selected",
//     "campaign_created_successfully": "Campaign created successfully",
//     "campaign_fetch_successfully": "Campaign fetch successfully",
//     "campaign_not_found": "Campaign not found",
//     "product_not_approved": "Product not approved",
//     "product_not_belongs_to_user": "Product not belongs to user"
//   }
